# Generated by Django 5.2.5 on 2025-12-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_lote",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("estado_lote", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "precio_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "precio_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "superficie_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("proyecto", models.CharField(blank=True, max_length=120, null=True)),
                ("manzana", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "medidas_lotes",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "cantidad_de_apartado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("dias_limite_apartado", models.IntegerField(blank=True, null=True)),
                (
                    "cantidad_enganche",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "cantidad_financiamiento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "pago_mensualidad",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "cantidad_liquidacion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("url_imagen_lote", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
