# Generated by Django 5.2.5 on 2025-09-23 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='lots.development')),
            ],
            options={
                'unique_together': {('development', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('block', models.CharField(blank=True, max_length=20)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frontage_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('depth_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Apartado'), ('sold', 'Vendido')], default='available', max_length=12)),
                ('svg_id', models.CharField(max_length=40, unique=True)),
                ('tooltip_label', models.CharField(blank=True, max_length=120)),
                ('plan_image', models.ImageField(blank=True, upload_to='lots/plans/')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='lots.stage')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
