# Generated by Django 5.2.5 on 2025-09-29 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Development",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "price_per_m2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "development",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="lots.development",
                    ),
                ),
            ],
            options={
                "unique_together": {("development", "number")},
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("block", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "front_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Frente (m)",
                    ),
                ),
                (
                    "back_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Fondo (m)",
                    ),
                ),
                (
                    "left_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Lado izq. (m)",
                    ),
                ),
                (
                    "right_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Lado der. (m)",
                    ),
                ),
                (
                    "frontage_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Frontage m",
                    ),
                ),
                (
                    "depth_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Depth m",
                    ),
                ),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "price_per_m2_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price per m2 override",
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("reserved", "Apartado"),
                            ("sold", "Vendido"),
                        ],
                        default="available",
                        max_length=12,
                    ),
                ),
                ("svg_id", models.CharField(max_length=40, unique=True)),
                ("tooltip_label", models.CharField(blank=True, max_length=120)),
                ("plan_image", models.ImageField(blank=True, upload_to="lots/plans/")),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="lots.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
