# Generated by Django 5.2.5 on 2025-10-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("area_m2", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("apartado", "Apartado"),
                            ("vendido", "Vendido"),
                        ],
                        default="disponible",
                        max_length=12,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="lots/%Y/%m/"),
                ),
                (
                    "apartado",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                (
                    "saldo_enganche",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("dias_limite_pago_enganche", models.PositiveIntegerField(default=5)),
                (
                    "precio_lista",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("plazo_default_meses", models.PositiveIntegerField(default=180)),
                (
                    "metodo_enganche_default",
                    models.CharField(default="Monto", max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "default_lot_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/default_lots/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Actualización", max_length=60)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payments", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=1)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_updates",
                        to="lots.lot",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="lot",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="lots.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lot",
            unique_together={("project", "number")},
        ),
    ]
