# Generated by Django 5.2.5 on 2025-09-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='back_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Fondo (m)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='front_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Frente (m)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='left_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Lado izq. (m)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='price_per_m2_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacío para usar el precio por m² de la etapa.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='right_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Lado der. (m)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio base por m² para esta etapa.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
