# Generated by Django 5.2.5 on 2025-09-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_lot_back_m_lot_front_m_lot_left_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='depth_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Depth m'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='frontage_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Frontage m'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='price_per_m2_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per m2 override'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
